apiVersion: apps/v1
kind: Deployment
metadata:
  name: category
spec:
  replicas: 2
  selector:
    matchLabels:
      app: category
  template:
    metadata:
      labels:
        app: category
    spec:
      containers:
        - name: category
          image: yoness/category
          envFrom:
            - configMapRef:
                name: category-configmap
          ports:
            - containerPort: 5500