apiVersion: v1
kind: Service
metadata:
  name: policy_model
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 1111
      targetPort: 1111
  selector:
    app: policy_model

